language: java

env:
  global:
  - bintrayUser=aurae
  - secure: VoY/zWE7itJmukAZt1Zw43jFzOk2ssWbpWhydYLiaRvplYVJvXTCSve4ZDpBhxPAlta2Kpfr9H8bwuaYCEtS+ovhi/q8Fo97YXiGdkHwEXJPal2n4O/XEj5hFr1BxIDTEwFBtGD/iQWZL/MVRaWFrfuMWajMZhDQkGz+DwRog4XCaw6UcEofW9kzfPG1T94C/bAIETrad4bfHKSbORVd2SbyPCFHkFH+YB/eWVqK2N5PuiPaet+EzcX/sxAFnwD6kF/uj3KxTlii/Yw8bM6LrPEWyyuMDglHN3LTevZ1CwT1oy8AUZaFzx246SL+Osn6t9WHoL1p3ltTS9O7sNL6WSyCP+JFYXF8iaF9USaINy/vcZFPsKdcCpgLPjSF/4mgXcjPc5KRao3tZOoamyvXuiGg7lfwUBl82t73ItlnSGgInAyUSesVrQ2gJNsVHdRqvOmVPBGXZ3lWb4GHksfQzLO210M7Tiu6leacWEbsYWmAsRER87qdUu7lY2b3wYJB7NhXX5AMZYINSzfCDVrThTWLXUU554D/3TmTKz/ROab2QxR/Qxh5i4ZJ/0MNdcM+qp8ORq6WlwGTUhCmD83XtiuBF3s/JW1WybsqC4Ppo23YuItqgfmMZWk75xLqpi48078vNgtEE/1YE2tvxd7ddfeT3eNLt7qrfj7Hu+r3L5A=
  - sonatypeUser=aurae
  - secure: C6eYUpK0VYvnJ7FGvGP+2EhqHvUxLAslY6rgjewUihagWxh4Yn8pY2jeDEXvuQHoErkyhOSyEHvUqfzdVa+SuQdo1Ldn9Pzm90wvatWAyQCIkrg9bCyqYgz1Fx2GpwJJCyrqOQVpeR8aYFi0gUh+YbsHiiquwvIMLxpNmtVLYnauDsLcy36nEsixWWAJBPRBchwW3+hukv2ZjvS8VVktxWa1WhknAlVSxDaYhgMRBFbOXZcneP4I2VOYIz4zKAS1tqXF72EEQf74+1Zray/DSbm+LFvLy0eiq3JptxLVk2w5DV3BzeQKQLW0vr2tULzOO8XnTJcwiBHHzMGeSCjRgLDqj6D4wbXAh8YDWVfTHkjWYMMGfSXpS6TWkJhtg3nsmqa7LcH3uyZHxhTrJF4JTjmNlF4XaXrTOZVlAhKgfojMqlEexFW/C1RZxoMry/K5d1N/Pm4/ayFyNHHQ6wpMxXsO8IWEGIU5mkVigpq+9UIhN/HtH6tZ+1UQKsE7bcAfoQcDnrBoeDxAHNetkkueSRt3GpaVMlil2+EzgdBkl6c3ns5GV06m9e9Y4JRW05M+q38o9NV/pbUaljIJ8WPHtIfbGw8L8jwrka/HtI6+7z8ev61Ot/A8DNEmoZb/kUtk2KgD0E5aQYBaQzhxy9EImQiIM5UY6qrcNuqjnZBf3qk=

jdk:
- oraclejdk8

script: ./gradlew clean check --info --stacktrace

after_success:
- ./scripts/deploy_snapshot.sh

deploy:
  provider: script
  script: ./scripts/deploy_release.sh
  on:
    tags: true
    repo: mannodermaus/retrofit-logansquare
